server:
  port: 8001

# https://resilience4j.readme.io/docs/getting-started-3
# https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker
resilience4j:
  retry:
    instances:
      # the name should match the constants in ResilientSupport.java
      hello:
        maxAttempts: 4
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
#          - org.springframework.web.client.HttpClientErrorException.NotFound
#          - org.springframework.web.client.HttpClientErrorException
          - org.springframework.web.client.RestClientException
#          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
  #      ignoreExceptions:
  #        - io.github.robwin.exception.BusinessException

  circuitbreaker:
    instances:
      iam:
        registerHealthIndicator: true
      twilio:
        registerHealthIndicator: true
      pccApis:
        registerHealthIndicator: true


echo:
  host: http://localhost:8001