server:
  port: 8002

# https://resilience4j.readme.io/docs/getting-started-3
# https://resilience4j.readme.io/docs/circuitbreaker#create-and-configure-a-circuitbreaker
resilience4j:
  circuitbreaker:
    instances:
      # the name should match values in ResilientSupport.java
      echo:
        registerHealthIndicator: true
